# Site settings
title: Winchell Wang
SEOTitle: Winchell.Wang Blog
header-img: img/home-bg.jpg
email: winchell.wang@outlook.com
description: "Winchell Wang Personal Blog"
keyword: "Winchell, winchell.wang, winchellwang, Winchell.Wang Blog, winchellwang blog, engineering"
url: "https://winchellwang.github.io/"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/winchellwang/winchellwang.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "ğŸ‡¨ğŸ‡³ ğŸ‡¦ğŸ‡º ğŸ‡ºğŸ‡¸ ğŸ‡¨ğŸ‡¦<br>ğŸ“· <a href='http://pixelfed.social/moax'>pixelfed.social/moax</a>"
sidebar-avatar: /img/avatar.png      # use absolute URL, seeing it's used in both `/` and `/about/`

# SNS settings
RSS: true
github_username: WinchellWang
#linkedin_username: None

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 5
exclude: ["less","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`

# Gems
# from PR#40, to support local preview for Jekyll 3.0
plugins: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important

# giscus
giscus:
    enable: true #æ˜¯å¦å¼€å¯giscusè¯„è®º
    repo: WinchellWang/winchellwang.github.io #ä»“åº“åç§°
    repo-id: R_kgDOHnDuaQ #ä»“åº“ID
    category: General #è¯„è®ºé»˜è®¤ç±»åˆ«
    category-id: DIC_kwDOHnDuac4CWMWd #åˆ†ç±»ID

# Gitalk
gitalk:
  enable: false    #æ˜¯å¦å¼€å¯Gitalkè¯„è®º
  clientID:                             #ç”Ÿæˆçš„clientID
  clientSecret:     #ç”Ÿæˆçš„clientSecret
  repo: winchellwang.github.io    #ä»“åº“åç§°
  owner: winchellwang    #githubç”¨æˆ·å
  admin: winchellwang
  distractionFreeMode: true #æ˜¯å¦å¯ç”¨ç±»ä¼¼FBçš„é˜´å½±é®ç½©


# Analytics settings
# Google Analytics
# ga_track_id: 'UA-99999999-9'            # Format: UA-xxxxxx-xx
# ga_domain: auto              # é»˜è®¤çš„æ˜¯ auto, è¿™é‡Œæˆ‘æ˜¯è‡ªå®šä¹‰äº†çš„åŸŸåï¼Œä½ å¦‚æœæ²¡æœ‰è‡ªå·±çš„åŸŸåï¼Œéœ€è¦æ”¹æˆauto

# Featured Tags
featured-tags: true                     # æ˜¯å¦ä½¿ç”¨é¦–é¡µæ ‡ç­¾
featured-condition-size: 2              # ç›¸åŒæ ‡ç­¾æ•°é‡å¤§äºè¿™ä¸ªæ•°ï¼Œæ‰ä¼šå‡ºç°åœ¨é¦–é¡µ

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# Friends
friends: [
    {
      title: "Martin Thissen",
      href: "https://medium.com/@martin-thissen"
    },{
      title: "å“²ç§‘æ–‡",
      href: "http://jerkwin.github.io"
    },{
      title: "Meta AI",
      href: "https://ai.facebook.com/results/?amp%3Bsort_by=most_recent&content_types%5B0%5D=publication"
    }
]
