# Site settings
title: Moax Wang
SEOTitle: Moax.Wang Blog
header-img: img/home-bg.jpg
email: moax.wang@outlook.com
description: "Moax Wang Personal Blog"
keyword: "Moax, moax.wang, moaxwang, Moax.Wang Blog, moaxwang blog, chemcial engineering"
url: "https://moaxwang.github.io/"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/MoaxWang/moaxwang.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Just a student.<br>Interested in photography.<br>âœ‰ï¸: moax.wang@outlook.com<br>ğŸ“·: https://pixelfed.social/moax"
sidebar-avatar: /img/avatar.png      # use absolute URL, seeing it's used in both `/` and `/about/`

# SNS settings
RSS: true
github_username: MoaxWang
#linkedin_username: None

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 5
exclude: ["less","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`

# Gems
# from PR#40, to support local preview for Jekyll 3.0
plugins: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important

# giscus
giscus:
    enable: true #æ˜¯å¦å¼€å¯giscusè¯„è®º
    repo: MoaxWang/moaxwang.github.io #ä»“åº“åç§°
    repo-id: R_kgDOHnDuaQ #ä»“åº“ID
    category: General #è¯„è®ºé»˜è®¤ç±»åˆ«
    category-id: DIC_kwDOHnDuac4CWMWd #åˆ†ç±»ID

# Gitalk
gitalk:
  enable: false    #æ˜¯å¦å¼€å¯Gitalkè¯„è®º
  clientID:                             #ç”Ÿæˆçš„clientID
  clientSecret:     #ç”Ÿæˆçš„clientSecret
  repo: moaxwang.github.io    #ä»“åº“åç§°
  owner: moaxwang    #githubç”¨æˆ·å
  admin: moaxwang
  distractionFreeMode: true #æ˜¯å¦å¯ç”¨ç±»ä¼¼FBçš„é˜´å½±é®ç½©


# Analytics settings
# Google Analytics
# ga_track_id: 'UA-99999999-9'            # Format: UA-xxxxxx-xx
# ga_domain: auto              # é»˜è®¤çš„æ˜¯ auto, è¿™é‡Œæˆ‘æ˜¯è‡ªå®šä¹‰äº†çš„åŸŸåï¼Œä½ å¦‚æœæ²¡æœ‰è‡ªå·±çš„åŸŸåï¼Œéœ€è¦æ”¹æˆauto

# Featured Tags
featured-tags: true                     # æ˜¯å¦ä½¿ç”¨é¦–é¡µæ ‡ç­¾
featured-condition-size: 2              # ç›¸åŒæ ‡ç­¾æ•°é‡å¤§äºè¿™ä¸ªæ•°ï¼Œæ‰ä¼šå‡ºç°åœ¨é¦–é¡µ

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# Friends
friends: [
    {
        title: "Huxpro",
        href: "http://huangxuan.me/"
    },{
        title: "Qiubaiying",
        href: "https://qiubaiying.github.io/"
    },{
        title: "Duter2016",
        href: "https://duter2016.github.io"
    },{
        title: "Richardurben",
        href: "https://richardurben.github.io"
    }
]
